event-management-system/Controllers/UserEventsController.cs
using event_management_system.Domain.Entities;
using event_management_system.Domain.Models;
using event_management_system.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Text.Json;

namespace event_management_system.Controllers
{
    public class UserEventsController : Controller
    {
        public IActionResult Index()
        {
            string userId = HttpContext.Request.Query["userId"]!;
            
            return View();
        }

        public IActionResult EventsUpcoming()
        {
            EventsServices eventsServices = new EventsServices();
            EventsModel eventsModel = eventsServices.GetAllUpcomingEvents();
            eventsServices.Dispose();
            //return Ok();
            return PartialView("EventCategory/EventsUpcoming", eventsModel);
        }

        public IActionResult EventsPrevious()
        {
            EventsServices eventsServices = new EventsServices();
            EventsModel eventsModel = eventsServices.GetAllPreviousEvents();
            eventsServices.Dispose();
            return PartialView("EventCategory/EventsPrevious", eventsModel);
        }

        public IActionResult EventInfo()
        {
            string EventID = HttpContext.Request.Query["id"];
            EventsServices eventsServices = new EventsServices();
            EventsModel eventsModel = eventsServices.GetEventInfoById(EventID);
            //EventsModel eventsModel = eventsServices;

            //get card info from url then find from list then return model
            return View(eventsModel);
        }

        [HttpPost]
        public IActionResult RegisterUser([FromBody]EventAttendee eventAttendee)
        {
            RegisterEventService registerEventService = new RegisterEventService();
            registerEventService.AddEventAttendee(eventAttendee);
            registerEventService.Dispose();
            return Ok();
        }

        public IActionResult MyEvents()
        {
            return View();
        }
    }

}

event-management-system/Controllers/UserHomeController.cs
using event_management_system.Domain.Models;
using event_management_system.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace event_management_system.Controllers
{
    public class UserHomeController : Controller
    {
        public IActionResult Index()
        {
            EventsServices eventsServices = new EventsServices();
            EventsModel eventsModel = eventsServices.GetAllUpcomingEvents();
            eventsServices.Dispose();
            string userId = HttpContext.Request.Query["userId"]!;
            TempData["UserId"] = userId;
            return View(eventsModel);
        }

        public IActionResult About()
        {

            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

event-management-system/Controllers/VisitorEventsController.cs
using event_management_system.Domain.Models;
using event_management_system.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Text.Json;

namespace event_management_system.Controllers
{
    public class VisitorEventsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult EventsUpcoming()
        {
            EventsServices eventsServices = new EventsServices();
            EventsModel eventsModel = eventsServices.GetAllUpcomingEvents();
            eventsServices.Dispose();
            //return Ok();
            return PartialView("EventCategory/EventsUpcoming", eventsModel);
        }

        public IActionResult EventsPrevious()
        {
            EventsServices eventsServices = new EventsServices();
            EventsModel eventsModel = eventsServices.GetAllPreviousEvents();
            eventsServices.Dispose();
            return PartialView("EventCategory/EventsPrevious", eventsModel);

        }

        public IActionResult EventInfo()
        {
            string EventID = HttpContext.Request.Query["id"];
            EventsServices eventsServices = new EventsServices();
            EventsModel eventsModel = eventsServices.GetEventInfoById(EventID);
            //EventsModel eventsModel = eventsServices;
            
            //get card info from url then find from list then return model
            return View(eventsModel);
        }
    }
}

event-management-system/Controllers/VisitorHomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Text.Json;
using event_management_system.Services;
using Org.BouncyCastle.Bcpg;
using event_management_system.Domain.Models;

namespace event_management_system.Controllers
{
    public class VisitorHomeController : Controller
    {
        public IActionResult Index()
        {
            EventsServices eventsServices = new EventsServices();
            EventsModel eventsModel = eventsServices.GetAllUpcomingEvents();
            eventsServices.Dispose();
            /*Debug.WriteLine("Controller");
            Debug.WriteLine(JsonSerializer.Serialize(eventsModel));
            Debug.WriteLine("Controller");*/
            return View(eventsModel);
        }

        public IActionResult Login() 
        {

            
            return View();
        }
        
        public IActionResult ValidateLogin([FromBody] UserCredential userCredential) 
        {

            // Debug.WriteLine(JsonSerializer.Serialize(userCredential));
            // get list of user then validate iif user or org
            string email = userCredential.Email!;
            string password = userCredential.Password!;

            AuthenticationService authenticationService = new AuthenticationService();
            authenticationService.AuthenticateStudent(email, password);
            if(!authenticationService.Model.IsAuthenticated)
            {
                authenticationService.AuthenticateOrganization(email, password);
                if(!authenticationService.Model.IsAuthenticated) 
                { 
                    return Ok();
                }
                else
                {
                    //string userId = authenticationService.Model.Organization!.OrganizationID!;
                    return Json(new { redirectTo = Url.Action("Index", "OrganizationHome", new { userId = authenticationService.Model.Organization!.OrganizationID! }) });
                }
               
            }
            else
            {
                //string userId = authenticationService.Model.Student!.StudentID!;
                return Json(new { redirectTo = Url.Action("Index", "UserHome", new { userId = authenticationService.Model.Student!.StudentID! }) });
            }



            
        }

        public IActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }

    public class UserCredential
    {
        public string? Email { get; set; }
        public string? Password { get; set; }
    }
}

event-management-system/Views/Shared/_OrganizationLayout.cshtml
@functions {
    public string IsPageActive(string controller, string action)
    {
        string isActive = "";

        if (Context.Request.RouteValues["controller"]!.ToString() == controller &&
            Context.Request.RouteValues["action"]!.ToString() == action)
        {
            isActive = "current";
        }

        return isActive;
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;500;600;700&display=swap" rel="stylesheet">
    <title>@ViewData["Title"] - TicketFlare</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="nav-logo-container">
                <h1 class="logo-name">TicketFlare</h1>
            </div>
            <div class="nav-list-container">
                <ul class="nav-list">
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="OrganizationHome" asp-action="Index">
                            <p class="text-glow-white @IsPageActive("OrganizationHome", "Index")">Home</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="OrganizationEvents" asp-action="Index">
                            <p class="text-glow-white @IsPageActive("OrganizationEvents", "Index")">Events</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="OrganizationHome" asp-action="About">
                            <p class="text-glow-white @IsPageActive("OrganizationHome", "About")">About</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="OrganizationHome" asp-action="Contact">
                            <p class="text-glow-white @IsPageActive("OrganizationHome", "Contact")">FAQs</p>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="nav-user-container">
                <div class="nav-user pill-box">
                    <p>OrgName</p>
                </div>
            </div>
        </nav>

        @* <div class="nav-bg">
        </div> *@
    </header>

    <div class="container">
        <main role="main" id="main-container">
            @RenderBody()
        </main>
    </div>

    <footer>
        <p>© COPYRIGHT 2024. ALL RIGHTS RESERVED.</p>
    </footer>
    
    <script src="~/js/organization.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

event-management-system/Views/Shared/_UserLayout.cshtml
@functions {
    public string IsPageActive(string controller, string action)
    {
        string isActive = "";

        if (Context.Request.RouteValues["controller"]!.ToString() == controller &&
            Context.Request.RouteValues["action"]!.ToString() == action)
        {
            isActive = "current";
        }

        return isActive;
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;500;600;700&display=swap" rel="stylesheet">
    <title>@ViewData["Title"] - TicketFlare</title>
    <link rel="stylesheet" href="~/css/user-site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="nav-logo-container">
                <h1 class="logo-name">TicketFlare</h1>
            </div>
            <div class="nav-list-container">
                <ul class="nav-list">
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="UserHome" asp-action="Index">
                            <p class="text-glow-white @IsPageActive("UserHome", "Index")">Home</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="UserEvents" asp-action="Index">
                            <p class="text-glow-white @IsPageActive("UserEvents", "Index")">Events</p>
                        </a>
                    </li>
                    @* <li>
                        <a class="nav-btn" asp-area="" asp-controller="UserEvents" asp-action="MyEvents">
                            <p class="text-glow-white @IsPageActive("UserEvents", "MyEvents")">My Events</p>
                        </a>
                    </li> *@
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="UserHome" asp-action="About">
                            <p class="text-glow-white @IsPageActive("UserHome", "About")">About</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="UserHome" asp-action="Contact">
                            <p class="text-glow-white @IsPageActive("UserHome", "Contact")">FAQs</p>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="nav-user-container">
                <div class="nav-user pill-box">
                    <p>UserName</p>
                </div>
            </div>
        </nav>

        @* <div class="nav-bg">
        </div> *@
    </header>

    <div class="container">
        <main role="main" id="main-container">
            @RenderBody()
        </main>
    </div>

    <footer>
        <p>© COPYRIGHT 2024. ALL RIGHTS RESERVED.</p>
    </footer>

    <script src="~/js/user.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

event-management-system/Views/Shared/_VisitorLayout.cshtml
@functions {
    public string IsPageActive(string controller, string action)
    {
        string isActive = "";

        if (Context.Request.RouteValues["controller"]!.ToString() == controller && Context.Request.RouteValues["action"]!.ToString() == action)
        {
            isActive = "current";
        }

        return isActive;
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;500;600;700&display=swap" rel="stylesheet">
    <title>@ViewData["Title"] - TicketFlare</title>
    <link rel="stylesheet" href="~/css/visitor-site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="nav-logo-container">
                <h1 class="logo-name">TicketFlare</h1>
            </div>
            <div class="nav-list-container">
                <ul class="nav-list">
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="VisitorHome" asp-action="Index">
                            <p class="text-glow-white @IsPageActive("VisitorHome", "Index")">Home</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="VisitorEvents" asp-action="Index">
                            <p class="text-glow-white @IsPageActive("VisitorEvents", "Index")">Events</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="VisitorHome" asp-action="About">
                            <p class="text-glow-white @IsPageActive("VisitorHome", "About")">About</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-btn" asp-area="" asp-controller="VisitorHome" asp-action="Contact">
                            <p class="text-glow-white @IsPageActive("VisitorHome", "Contact")">FAQs</p>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="nav-user-container">
                <a class="nav-user pill-box" asp-area="" asp-controller="VisitorHome" asp-action="Login">
                    <p>Sign in</p>
                </a>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" id="main-container">
            @RenderBody()
        </main>
    </div>

    <footer>
        <p>© COPYRIGHT 2024. ALL RIGHTS RESERVED.</p>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>