event-management-system/Controllers/OrganizationEventsController.cs
using event_management_system.Domain.Models;
using event_management_system.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Diagnostics;
using System.Diagnostics;
using event_management_system.Domain.Entities;
using System.Text.Json;
using static System.Net.Mime.MediaTypeNames;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.Logging;
using event_management_system.Domain.Repositories;

namespace event_management_system.Controllers
{

    public class OrganizationEventsController : Controller
    {

        private readonly ILogger<OrganizationEventsController> _logger;

        public OrganizationEventsController(ILogger<OrganizationEventsController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            string userID = HttpContext.Request.Query["userId"]!;
            ViewData["OrganizationID"] = userID;
            return View();
        }

        public IActionResult ContentCreation()
        {
            string userID = HttpContext.Request.Query["userId"]!;
            ViewData["OrganizationID"] = userID;
            return View();
        }


        [HttpPost]
        public IActionResult SendTextData([FromBody]CreateEventData eventEntity)
        {
            if (!ModelState.IsValid)
            {
                // The model is not valid, log validation errors
                var errors = ModelState.Values
                    .SelectMany(v => v.Errors.Select(e => e.ErrorMessage));

                foreach (var error in errors)
                {
                    _logger.LogError($"Validation Error: {error}");
                }

                return BadRequest(new { Message = "Validation failed", Errors = errors });
            }



            Debug.WriteLine(JsonSerializer.Serialize(eventEntity));
            Event eventData = new Event();


            eventData.EventID = eventEntity.EventID;
            eventData.EventNatureID = eventEntity.EventNatureID;
            eventData.EventStatusID = eventEntity.EventStatusID;
            eventData.OrganizationID = eventEntity.OrganizationID;
            eventData.Venue = eventEntity.Venue;
            eventData.Title = eventEntity.Title;
            eventData.DatePosted = eventEntity.DatePosted;
            eventData.DateStart = eventEntity.DateStart;
            eventData.DateEnd = eventEntity.DateEnd;
            eventData.ParticipantNumber = eventEntity.ParticipantNumber;
            eventData.EventType = eventEntity.EventType;
            eventData.ContactPerson = eventEntity.ContactPerson;
            eventData.ContactNumber = eventEntity.ContactNumber;
            eventData.FeedbackLink = eventEntity.FeedbackLink;
            eventData.PaymentLink = eventEntity.PaymentLink;
            eventData.Description = eventEntity.Description;

            eventData.DatePosted = DateTime.Now;
            Debug.WriteLine(JsonSerializer.Serialize(eventData));

            EventCreateEditService eventCreateEditService = new EventCreateEditService();

            eventCreateEditService.AddEvent(eventData);
            eventCreateEditService.Dispose();


            return Ok();
        }


        public IActionResult EventsUpcoming() 
        {
            string userID = HttpContext.Request.Query["userId"]!;

            EventsServices eventsServices = new EventsServices();
            EventsModel eventsModel = eventsServices.GetAllUpcomingEventsByOrganizationID(userID);
            eventsServices.Dispose();

            // get list of upcoming based on orgID then return as model
            return PartialView("EventCategory/EventsUpcoming", eventsModel);
            // return PartialView("EventCategory/EventsUpcoming", modelHere);
        }

        public IActionResult EventsPrevious()
        {
            string userID = HttpContext.Request.Query["userId"]!;

            EventsServices eventsServices = new EventsServices();
            EventsModel eventsModel = eventsServices.GetAllPreviousEventsByOrganizationID(userID);
            eventsServices.Dispose();

            // get list of previous based on orgID then return as model
            return PartialView("EventCategory/EventsPrevious", eventsModel);
        }

        public IActionResult EventMain()
        {
            string userID = HttpContext.Request.Query["userId"]!;
            ViewData["OrganizationID"] = userID;


            string eventID = HttpContext.Request.Query["eventId"]!;
            TempData["EventId"] = eventID;
            ViewData["EventID"] = eventID;
            return View();
        }



        public IActionResult EventDetails()
        {
            // Use the name 'eventId' to match the query parameter
            string eventId = HttpContext.Request.Query["eventId"]!;

            EventCreateEditService eventsService = new EventCreateEditService();
            EventCreateEditModel eventCreateEditModel = eventsService.GetEventData(eventId);
            eventsService.Dispose();

            return PartialView("EventManagement/EventDetails", eventCreateEditModel);
        }

        [HttpPost]
        public IActionResult EditEvent([FromBody]Event eventEntity)
        {
            eventEntity.DatePosted = DateTime.Now;
            EventCreateEditService editService = new EventCreateEditService();
            editService.UpdateEvent(eventEntity);
            editService.Dispose();

            return Ok();
        }


        public IActionResult EventAttendanceLog()
        {
            // Use the name 'eventId' to match the query parameter
            string eventId = HttpContext.Request.Query["eventId"]!;
            AttendanceLogService attendanceLogService = new AttendanceLogService(eventId);
            AttendanceLogModel attendanceLogModel = attendanceLogService.Model;
            attendanceLogService.Dispose();

            return PartialView("EventManagement/EventAttendanceLog", attendanceLogModel);
        }

        public IActionResult TimeInAttendanceLog([FromBody]TimeInEntity timeInEntity) 
        {
            timeInEntity.TimeIn = DateTime.Now;

            Debug.WriteLine(JsonSerializer.Serialize(timeInEntity));
            AttendanceLogService attendanceLogService = new AttendanceLogService();
            attendanceLogService.TimeIn(timeInEntity);
            return Ok();
        }
        
        public IActionResult TimeOutAttendanceLog([FromBody]TimeOutEntity timeOutEntity) 
        {
            timeOutEntity.TimeOut = DateTime.Now;

            Debug.WriteLine(JsonSerializer.Serialize(timeOutEntity));
            AttendanceLogService attendanceLogService = new AttendanceLogService();
            attendanceLogService.TimeOut(timeOutEntity);
            return Ok();
        }



        public IActionResult EventAttendees()
        {
            string eventId = HttpContext.Request.Query["eventId"]!;

            AttendeeManagementService attendeeManagementService = new AttendeeManagementService();
            AttendeeManagementModel attendeeManagementModel = attendeeManagementService.GetAllAttendees(eventId);
            attendeeManagementService.Dispose();

            return PartialView("EventManagement/EventAttendees", attendeeManagementModel);
        }

        public IActionResult CreateTicket([FromBody]EventIDModel eventID)
        {
            Debug.WriteLine(eventID.EventID);
            AttendeeManagementService attendeeManagementService = new AttendeeManagementService();
            attendeeManagementService.GenerateTickets(eventID.EventID);
            attendeeManagementService.Dispose();

            return Ok();
        }



        public IActionResult UpdateAttendeeStatus([FromBody]EventAttendee eventAttendee)
        {
            Debug.WriteLine(JsonSerializer.Serialize(eventAttendee));

            AttendeeManagementService attendeeManagementService = new AttendeeManagementService();
            attendeeManagementService.UpdateStudentApproveStatus(eventAttendee);
            attendeeManagementService.Dispose();
            return Ok();
        }



    }

    public class EventIDModel
    {
        public string? EventID { get; set; }
    }

    public class EventDetailsModel
    {
        /* public string? EventID { get; set; }
         public string? EventNatureID { get; set; }
         public string? EventStatusID { get; set; }
         public string? OrganizationID { get; set; }
        *//* public string DateStart { get; set; }
         public string DateEnd { get; set; }*//*
         public string? Venue { get; set; }
         public string? Title { get; set; }
         public int? ParticipantNumber { get; set; }
         public string? EventType { get; set; }
         public string? ContactPerson { get; set; }
         public string? ContactNumber { get; set; }
         public string? FeedbackLink { get; set; }
         public string? PaymentLink { get; set; }
         public string? Description { get; set; }*/
        public EventDetailsModel() { }
        public EventDetailsModel(string eventID,
            string eventNatureID,
            string eventStatusID,
            string organizationID,
            string venue,
            string title,
            int participantNumber,
            string eventType,
            string contactPerson,
            string contactNumber,
            string feedbackLink,
            string paymentLink,
            string description)
        {
            EventID = eventID;
            EventNatureID = eventNatureID;
            EventStatusID = eventStatusID;
            OrganizationID = organizationID;
            Venue = venue;
            Title = title;
            ParticipantNumber = participantNumber;
            EventType = eventType;
            ContactPerson = contactPerson;
            ContactNumber = contactNumber;
            FeedbackLink = feedbackLink;
            PaymentLink = paymentLink;
            Description = description;
        }

event-management-system/Views/OrganizationEvents/ContentCreation.cshtml
@{
    ViewData["Title"] = "Content Creation";
    Layout = "~/Views/Shared/_OrganizationLayout.cshtml";
    var OrganizationID = ViewData["OrganizationID"];
}

<div class="nav-bg">
</div>

<div class="introduction-container event-introduction" id="event-information-introduction">
    <div class="introduction-content standard-container">
        <div class="introduction-text-container">
            <h1 class="introduction-text-title large-text"><span>EVENTS CONTENT CREATION</span></h1>
            <p class="introduction-text-p">
                Welcome to the Events Tab, your go-to destination for a holistic view of the university's colorful event scene! Whether you're gearing up for upcoming activities, immersing yourself in ongoing happenings, or reminiscing about past memorable events, this section has got you covered. Organizers, dive into the details, from event names to dates and locations, all neatly organized for your convenience. Ready to make waves of your own? The "Create Event" button awaits, empowering you to kickstart your event planning journey. Experience the ease of navigation and a centralized hub designed to elevate your event management game. Welcome to the heart of the action, where every detail is at your fingertips!
            </p>
        </div>
    </div>
</div>

<div class="content-navigation small-container" id="create-event-information">
    <div class="current-content create-event-background">
        <h1 class="medium-text" id="event-content-btn">EVENT CONTENT</h1>
    </div>
</div>

<div class="event-content-container small-container">

    <div class="event-content-header">
        <h1 class="form-title text-glow-white">CREATE YOUR EVENT!</h1>
    </div>


    <form action="" id="upload-event-form" organization-id="@OrganizationID">

        <fieldset class="add-image" >
            <p>Image</p>
            <div id="upload-container">
                <div id="preview-container"></div>
                <div class="upload-button-container">
                    <label for="file-input" class="upload-button">
                        Choose Image/s
                    </label>
                    <input type="file" id="file-input" class="file-input" accept="image/*" multiple>
                </div>
            </div>
        </fieldset>

        <fieldset class="event-details">

            <div class="form-row">
                <div>
                    <label for="eventTitle">Event Title</label>
                    <input type="text" name="eventTitle" id="eventTitle">
                </div>
            </div>

            <div class="form-row">
                <div>
                    <label for="startDateTime">Start Date/Time</label>
                    <input type="datetime-local" name="startDateTime" id="startDateTime">
                </div>

                <div>
                    <label for="endDateTime">End Date/Time</label>
                    <input type="datetime-local" name="endDateTime" id="endDateTime">
                </div>
            </div>

            <div class="form-row">
                <div>
                    <label for="venue">Venue</label>
                    <input type="text" name="venue" id="venue">
                </div>

                <div>
                    <label for="participantNumber">Number of Participants</label>
                    <input type="number" name="participantNumber" id="participantNumber">
                </div>
            </div>

            <div class="form-row">
                <div>
                    <label for="eventNature">Nature of Event</label>
                    <br>
                    <!-- <input type="text" name="venue" id="venue"> -->
                    <select name="eventNature" id="eventNature">
                        <option value="" disabled selected hidden>Event Nature</option>
                        <option value="1">Curricular</option>
                        <option value="2">Co-curricular</option>
                        <option value="3">Non-curricular</option>
                    </select>
                </div>

                <div>
                    <label for="eventType">Type of Event</label>
                    <input type="text" name="eventType" id="eventType">
                </div>
            </div>

            <div class="form-row">
                <div>
                    <label for="contactPerson">Contact Person</label>
                    <input type="text" name="contactPerson" id="contactPerson">
                </div>

                <div>
                    <label for="contactNumber">Contact Number</label>
                    <input type="text" name="contactNumber" id="contactNumber">
                </div>
            </div>

            <div class="form-row">
                <div>
                    <label for="feedbackLink">Feedback Link</label>
                    <input type="text" name="feedbackLink" id="feedbackLink">
                </div>

                <div>
                    <label for="paymentLink">Payment Link</label>
                    <input type="text" name="paymentLink" id="paymentLink">
                </div>
            </div>

            <div class="form-row">
                <div>
                    <label for="description">Description</label>
                    <textarea type="text" name="description" id="description" rows="10"></textarea>
                </div>
            </div>

        </fieldset>

    </form>
    <div class="btn-group">
        <button class="pill-btn pill-box" id="preview-event">Preview Event</button>
        <button class="pill-btn pill-box" id="submit-event">Submit Event</button>
    </div>
    
</div>

<script src="~/js/event-creation.js"></script>

event-management-system/Views/OrganizationEvents/EventMain.cshtml
@{
    var EventID = ViewData["EventID"];
    var OrganizationID = ViewData["OrganizationID"];
    Layout = "~/Views/Shared/_OrganizationLayout.cshtml";
}

<div class="nav-bg">
</div>

<div class="introduction-container event-introduction" id="event-information-introduction">
    <div class="introduction-content standard-container">
        <div class="introduction-text-container">
            <h1 class="introduction-text-title large-text"><span>EVENTS EDIT AND PROCESSING</span></h1>
            <p class="introduction-text-p">
                The Event Creation and Processing Tab is the epicenter of your event management journey on TicketFlare! Here, you wield the power to shape your event's narrative, inputting essential details that showcase its uniqueness. Navigate effortlessly through event creation, providing a smooth experience for organizers. Monitor attendees with precision, approving their participation with a simple checkbox. Dive into the attendance tracking, where every scan is documented, allowing you to view the time in and time out of participants who've embraced the event through QR code verification. With TicketFlare's powerful tools, event management becomes an art form, and your events take center stage with efficiency and accuracy.
            </p>
        </div>
    </div>
</div>

<div class="content-navigation standard-container" id="event-information-navigation">
    <div class="current-content" id="current-event-information-navigation"></div>

    <button data-type="Details">
        <h1 class="medium-text" id="event-info-btn">EVENT DETAILS</h1>
    </button>

    <button data-type="Attendees">
        <h1 class="medium-text" id="event-info-btn">ATTENDEES</h1>
    </button>

    <button data-type="AttendanceLog">
        <h1 class="medium-text" id="event-info-btn">ATTENDANCE LOG</h1>
    </button>
</div>

<div class="subcontent-container" id="subcontent-container" event-id="@EventID" organization-id="@OrganizationID">
    @* @await Html.PartialAsync("EventManagement/EventAttendees"); *@
</div>

@section Scripts {
    <script src="~/js/event-information.js"></script>
}

event-management-system/Views/OrganizationEvents/Index.cshtml
@{
    ViewData["Title"] = "Events";
    Layout = "~/Views/Shared/_OrganizationLayout.cshtml";
}

<div class="nav-bg">
</div>

<div class="introduction-container event-introduction" id="event-list-introduction">
    <div class="introduction-content standard-container">
        <div class="introduction-text-container">
            <h1 class="introduction-text-title large-text"><span>ORGANIZATION EVENTS</span></h1>
            <p class="introduction-text-p">
                Welcome to the Events Tab, your go-to destination for a holistic view of the university's colorful event scene! Whether you're gearing up for upcoming activities, immersing yourself in ongoing happenings, or reminiscing about past memorable events, this section has got you covered. Organizers, dive into the details, from event names to dates and locations, all neatly organized for your convenience. Ready to make waves of your own? The "Create Event" button awaits, empowering you to kickstart your event planning journey. Experience the ease of navigation and a centralized hub designed to elevate your event management game. Welcome to the heart of the action, where every detail is at your fingertips!
            </p>
        </div>
        <div class="create-event-container">
            <h2 class="create-event-text medium-text text-glow-white">MAKE YOUR OWN EVENT</h2>
            <a id="createEventLink" class="create-event-btn pill-box small-text" asp-area="" asp-controller="OrganizationEvents" asp-action="ContentCreation">
                Create Event
            </a>
        </div>
    </div>
</div>

<div class="content-navigation standard-container" id="event-list-navigation">
    <div class="current-content" id="current-event-list-navigation"></div>
    <button data-type="Upcoming">
        <h1 class="medium-text" id="upcoming-btn">UPCOMING EVENTS</h1>
    </button>
    <button data-type="Previous">
        <h1 class="medium-text" id="previous-btn">PREVIOUS EVENTS</h1>
    </button>
</div>

<div class="subcontent-container" id="subcontent-container">
    @* Insert Partial Views *@
</div>

@section Scripts {
    <script src="~/js/events.js"></script>
}